### ISSUE TITLE
Not working on 1.14

### ISSUE THREAD

**Issue by roopekoo** [netherfoam/MaxBans-Plus#66]
I am currently using paper spigot build-119 1.14.3 server and tried to test if plugins would work in 1.14. 
I am using maxBansPlus 1.8 
This is the error message I got:
https://pastebin.com/pj4tzTfc

I hope this can be fixed soon.

**Comment by netherfoam** [comment]
Can I get you to give [this](maxgamer.org/plugins/maxbans-plus-1.9.jar) version a shot and see if it resolves your issues?

**Comment by roopekoo** [comment]
Cannot proceed. Page says "not found"

**Comment by netherfoam** [comment]
Whoops, I should test links before I give them out!

try [this](http://maxgamer.org/plugins/maxbans-plus-1.9.jar) instead lol.

**Comment by roopekoo** [comment]
This seems to work as intended. Loads normally; Bans, mutes, and warnings work also as they should.
Thank you so much! :)
