### ISSUE TITLE
[Question] Does MaxBans Plus ban the username or the UUID?

### ISSUE THREAD

**Issue by 10Meisterbaelle** [netherfoam/MaxBans-Plus#76]

**Comment by 10Meisterbaelle** [comment]
Found it out!

**Comment by netherfoam** [comment]
Depends if you're online or offline. The relevant code is [here](https://github.com/netherfoam/MaxBans-Plus/blob/master/src/main/java/org/maxgamer/maxbans/service/UserService.java#L85)

If the server is in offline mode, I identify the player with their name.
If the server is online, I use the UUID!

**Comment by netherfoam** [comment]
Ah, well done!
